{% extends "quaid_base.html" %}

{% block title %}Quaid{% endblock %}

{% block description %}Quaid's validation module handles errors returned from your server.
It uses the Bassistance validation jQuery plugin to push these errors through your form
validation.{% endblock %}

{% block keywords %}quaid, jquery, javascript, form, form handling, validation,
errors, error handling{% endblock %}

{% block sidebar %}

{% endblock %}

{% block scriptfiles %}
{{block.super}}
<style>
    #example1 .results {display: none;}
</style>
{% endblock %}

{% block script %}
{{block.super}}

Q.currentPage = 'validation';
$(document).ready(function(){
    $('#example1 form').submit(function(){
        var f = $(this);
        $.ajax({
            url: f.attr('action'),
            dataType: 'json',
            data: f.formSerialize(),
            type: 'POST',
            success: function(){
                $.info('success called with params', arguments);
            },
            error: function(){
                $.info('error called with params', arguments);
            },
            applicationError: function(){
                $.info('applicationError called with params', arguments);
            }
        });
        return false;
    });
    
    $('#example2').AsyncForm({
        validationOptions:{
            rules: {
                // This 'asyncError' validator enables async validation.
                // Quaid will implicitly add this to any names that have
                // any other rules. You can turn it off with
                // asyncError: False
                email: {asyncError: true}
            }
        },
        onSuccess: function(data){
            this.container.find('.results').show().text(
                'Hey, good job ' + data.results.email
            );
        },
        onFail: function(){
            this.container.find('.results').hide();
        }
    });
});

{% endblock %}

{% block entrytitle %}Quaid Validation module{% endblock %}
{% block entrycontent %}

<p>Sometimes the server side of your web app produces errors. These may be intentional
and destined for the user, like form validation or authorization errors, or they may be
unintentional internal server errors. Quaid's <code>Validation</code> module implements
a scheme for handling these errors from async requests. This
scheme has two parts: culling errors from the response for each request and attempting to
do something with them via integration with the
<a href="http://bassistance.de/jquery-plugins/jquery-plugin-validation/">Bassistance validation plugin</a>.</p>

<h2 id="basics">Basics</h2>

<p>Quaid's validation module installs a shim in between each request and the callbacks your
application receives. It does this by patching jQuery's $.ajax function. A new requirement is placed
on the server's response. Quaid needs to know whether or not your response is a success or fail.
When your server says all is peachy, you simply return your data.
Quaid will pass it on to your success handler as if there
were no shim at all</p>

<pre class="prettyprint">
// Server says:
// 200 OK
{someData: 23, ...}
</pre>

<p>When your server has an error you can do one of two things: set a <code>status</code> param
to <code>fail</code> or return a response with HTTP status code somewhere in the 400s.
You return your errors in a list of dictionaries under the response's <code>error</code>
field. Each error must have, at a minimum, a <code>message</code> field.</p>

<pre class="prettyprint">
// Server says:
// 200 OK
{
    status: 'fail', 
    errors: [
        {message: 'something bad happened!'},
        {message: 'Error 2!'}
    ]
}

// Or server says:
// 400 Bad Request
{ 
    errors: [
        {message: 'something bad happened!'},
        {message: 'Error 2!'}
    ]
}
</pre>

<p>When an error response like above is generated, Quaid will call a brand new
callback available to <code>$.ajax</code>: <code>applicationError</code>. Quaid will pass the
errors returned from the server to this function.</p>

<pre class="prettyprint">
$.ajax({
    dataType: 'json',
    applicationError: function(errorType, errors){
        // errorType will be 'applicationerror' in the case
        // of the above server response
        $.info('Application Error! type: ', errorType,
               '; errors: ', errors);
    }
})
</pre>

<p>There are two different types of errors Quaid cares about: general errors
and field errors. Field errors are errors attributed to a particular form
field. They would be the results of some form validation scheme on the server side. General
errors are anything else. The errors in the response examples above are general errors. Quaid
splits field errors from general errors and passes them into your applicationError callback.</p>

<pre class="prettyprint">
// Server says:
// 400 Bad Request
{ 
    errors: [
        {message: 'Something bad happened!'},
        {message: 'Your url is not valid', field: 'url'},
        {
            message: 'Address "bob@omfg.com" is already taken',
            field: 'email'
        }
    ]
}

$.ajax({
    dataType: 'json',
    applicationError: function(errorType, errors){
        // errors will be:
        // {
        //     general: [{message: 'Something bad happened!'}],
        //     field: [
        //       {message: 'Your url is not valid', field: 'url'},
        //       {
        //         message: 'Address "bob@omfg.com" is already taken',
        //         field: 'email'
        //       }
        //     ]
        // }
        $.info('Application Error! type: ', errorType,
               '; errors: ', errors);
    }
})
</pre>

<p>You can pass any other data back from the server with your errors. At AdRoll,
we pass back code and value fields with general errors, and debug info elsewhere
in the response.</p>

<pre class="prettyprint">
// Our server says:
// 400 Bad Request
{ 
    errors: [
        {message: 'Error!', code: 256, value: 'related to code param'},
        {message: 'Bad name', field: 'name'}
    ],
    debug: {queries: 23, query_time: 0.34}
}
</pre>

<h2 id="handling_errors">Handling Errors</h2>

<p>Every error returned from the server should be marked 'handled' at some point in the
response's callback chain. Quaid maintains a list of all the errors returned by the server. This list is wrapped by
an object called <code>Q.asyncErrors</code>. It has a few methods</p>

<pre class="prettyprint">
// Used by the validation module.
Q.asyncErrors.add(errors, form)

// Marks an error as handled. Accepts a single error or a list of them.
Q.asyncErrors.handle(errors) 

// A way to get all the unhandled errors.
Q.asyncErrors.getUnhandledErrors()

// Clear all errors
Q.asyncErrors.clear()
</pre>

<p>On each error response,
<code>Q.asyncErrors.add(errors)</code> will be called and the errors will all be placed into the list.
If you display or otherwise handle an error in your <code>applicationError</code> callback,
you can call <code>Q.asyncErrors.handle(error)</code> on the error to notify the rest of the
application that the error has been handled.</p>

<p>Field errors will be marked automatically if you have the
<a href="http://bassistance.de/jquery-plugins/jquery-plugin-validation/">Bassistance validation plugin</a>
installed. Quaid will pass the them to the plugin, and Quaid's special validator will
mark them as handled. More on that <a href="#validation">later</a>.</p>

<p>At the end of the applicationError callback chain, Quaid will call a global function
<code>Q.handleApplicationErrors</code> with all the remaining unhandled errors. This thing
allows you to make sure no errors slip through the cracks. You are encouraged to
override this to handle global errors in your own way. At AdRoll, we have the errors display
in a position:fixed error container. The default behavior is to log some
warning messages.</p>

<pre class="prettyprint">
Q.handleApplicationErrors = function(errors){
    for(var i = 0; i < errors.length; i ++)
        $.warn('Unhandled async application error "',
                errors[i].message ,'" :', errors[i]);
    Q.asyncErrors.handle(errors);
};
</pre>

<h2 id="server_errors">Server Errors</h2>

<p>Server errors (400+, 500+) are already handled by jQuery's <code>error</code> callback
in the <code>$.ajax</code> options. Quaid doesn't mess with this. You will still get 
<code>error</code> callbacks. You will also get <code>applicationError</code> callbacks.
In the case of a 500+ server error, you will get a <code>applicationError</code> call with the
first argument 'servererror'.</p>

<p>After your <code>applicationError</code> function has been called
a global method <code>Q.handleServerError</code> is called.

Like <code>Q.handleApplicationErrors</code>, you are encouraged to replace <code>Q.handleServerError</code>
with your own function to handle all 500+ server errors.
You can provide a nice error message to your users when they bump against an error. At AdRoll,
we display a generic message to normal users, and to engineers, we put the server's response
in a little debug bar we wrote which will display the stack trace. Very handy.
The default implementation will display an alert box.
</p>

<pre class="prettyprint">
// data is the response's parsed data
// Other options are the same as jQuery's default error callback.
Q.handleServerError = function(data, xhr, status, errorThrown){
    alert('Oops. An error occurred. Our team has been notified!');
};
</pre>

<h2>Error Handling and Callback Example</h2>

<div id="example1" class="example">
    <h4>Error Example</h4>
    
    <p>Open up your console and check out what the server returns and how it is handled
    by Quaid.</p>
    
    <div class="form-magic">
        <form method="post" action="/quaid/error_example">
            <div>
                <label>Error Type</label>
                <select name="errtype">
                    <option value="none">None (success!)</option>
                    <option value="fail">200 OK fail</option>
                    <option value="bad_req">400 Bad Request (general error)</option>
                    <option value="bad_req_field">400 Bad Request (field error)</option>
                    <option value="server">500 Server Error</option>
                    <option value="not_found">404 Not Found</option>
                </select>
            </div>
            
            <div><input type="submit" value="Submit"/></div>
        </form>
    </div>
</div>

<pre class="prettyprint">
$('#example1 form').submit(function(){
    var f = $(this);
    $.ajax({
        url: f.attr('action'),
        dataType: 'json',
        data: f.formSerialize(),
        type: 'POST',
        success: function(){
            $.info('success called with params', arguments);
        },
        error: function(){
            $.info('error called with params', arguments);
        },
        applicationError: function(){
            $.info('applicationError called with params', arguments);
        }
    });
    return false;
});
</pre>

<h2 id="validation">Validation</h2>

<p>Quaid integrates with the
<a href="http://bassistance.de/jquery-plugins/jquery-plugin-validation/">Bassistance validation plugin</a>.
It is a very useful, extensible and well written framework for handling client side form
validation. Quaid provides a way to transparently handle server side validation as well with
the validation plugin. Example first.</p>

<div id="example2" class="example">
    <h4>Validation Example</h4>
    
    <p>This simply takes an email address. It can fail in a multitude of ways: if no email is
    present, if you enter bob@zomg.com, if it is longer than 25 characters, and if it is not
    a valid email address. All validation is done on the server. Check out your console.</p>
    
    <div class="form-magic">
        <form method="post" action="/quaid/validation_example">
            <div>
                <label>Email</label>
                <input type="text" name="email"/>
            </div>
            
            <div><input type="submit" value="Submit"/></div>
            
        </form>
        
        <div class="results"></div>
    </div>
</div>

<pre class="prettyprint">
$('#example2').AsyncForm({
    validationOptions:{
        rules: {
            // This 'asyncError' validator enables async validation.
            // Quaid will implicitly add this to any names that have
            // any other rules. You can turn it off with
            // asyncError: False
            email: {asyncError: true}
        }
    },
    onSuccess: function(data){
        this.container.find('.results').show().text(
            'Hey, good job ' + data.results.email
        );
    },
    onFail: function(){
        this.container.find('.results').hide();
    }
});
</pre>

<h3>How?</h3>

<p>How does this work? Quaid's patched $.ajax function collects all the field errors when an
error comes back from the server. It passes them to 
<code>Q.asyncErrors</code>, then revalidates the form. When the form is revalidated,
Quaid's <code>asyncError</code> validator method will get called by the validation framework
and will look in <code>Q.asyncErrors</code> for errors. If it finds any, it passes
them back to the validation framework which displays them! It will mark any errors
it can find a field for as handled via <code>Q.asyncError.handle()</code>.</p>

{% endblock %}